// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alfdirzvingjzmikwpmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsZmRpcnp2aW5nanptaWt3cG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDk1MzcsImV4cCI6MjA2MDcyNTUzN30.X4Kh_ggE1pf19hw0N9yTiUa5xoh4Mten7_WxkVwu1Bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);